### ISSUE TITLE
got an error in toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by justinlazaro-ubidy** [react-cropper/react-cropper#100]
Hi im using cdn image, but i got an error toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported. also i set checkCrossOrigin={true}

**Comment by EdoAPP** [comment]
Hi @justinlazaro-ubidy , I'm also getting same error when I try `toDataURL()`, could you solve the problem?

**Comment by pegasus1982** [comment]
I have same problem.

**Comment by Abuitime** [comment]
Anyone solve this issue?
