### ISSUE TITLE
max-width: 100% is not applied to img element

### ISSUE THREAD

**Issue by omasback** [react-cropper/react-cropper#101]
The [cropper.js](https://github.com/fengyuanchen/cropperjs#getting-started) docs say it's very important to max-width the source img, but this component does not do it. If there is a reason for not inlining this style, can you please provide a classname prop for the img so we may implement it via stylesheet. I'm using JSS so targeting it via global selectors is impractical.

Should be a one-liner. I will try to submit a PR if I have time

```javascript
/* Limit image width to avoid overflow the container */
img {
  max-width: 100%; /* This rule is very important, please do not ignore this! */
}
```

**Comment by Gogn** [comment]
I spent a few hours trying to properly size container.
Fixed this by editing source in node_modules:

`_react.default.createElement("img", {
        crossOrigin: crossOrigin,
        ref: function ref(img) {
          _this3.img = img;
        },
        src: src,
        alt: alt === undefined ? 'picture' : alt,
        style: {
          opacity: 0,
          **maxWidth: '100%'**
        }`

**Comment by Gogn** [comment]
Open pull request:
https://github.com/roadmanfong/react-cropper/pull/153/commits

**Comment by shekhar-shubhendu** [comment]
Closing as the PR is already merged.
