### ISSUE TITLE
Focal/Focus Point 

### ISSUE THREAD

**Issue by watzak** [react-cropper/react-cropper#102]
Hello Steven aka @roadmanfong 

I really like your work!
I just want to ask u if u are planning to include/implement a focal point in the future? Is this something u want to have within your project?

Something like this?
<img width="578" alt="screen shot 2018-08-10 at 22 08 11" src="https://user-images.githubusercontent.com/8505970/43979177-25250e36-9cea-11e8-8c6a-2299c02e65d3.png">

Thanx for your answer in advance!

Cheers Klausi

**Comment by gigeos** [comment]
I did it with this library. If you are interested, I can open a PR for that

**Comment by frisi** [comment]
definitely interested @gigeos. would you mind to share a link?
