### ISSUE TITLE
Not able to write test case for cropper using enzyme

### ISSUE THREAD

**Issue by anilljoshi** [react-cropper/react-cropper#104]
Here is my function which is working fine but during test-case it's not working properly

import React, { Component } from 'react';
import Cropper from 'react-cropper';
import { Button, Modal, ModalFooter, ModalBody } from 'reactstrap';
import css from './cropper.css';
import clientInfo from 'assets/config.json';

class CropperContainer extends Component{

	_crop=()=>{           
	    this.refs.cropper.disable();
	    let croppedImg;
	    if(this.props.cropperType === "logo"){ 
	    	 console.log(this.refs.cropper) 
	        let logoOriginal = this.refs.cropper.getCroppedCanvas().toDataURL('image/png');
	        document.getElementById('logo').src=logoOriginal;
	        croppedImg = logoOriginal.replace(/^data:image\/[\w,\d,\W,\D]+;base64,/, "");       
	    }
	    if(this.props.cropperType === "banner"){
	      let bannerOriginal = this.refs.cropper.getCroppedCanvas().toDataURL('image/jpeg');
	      document.getElementById('banner').style.backgroundImage ='url('+bannerOriginal+')';
	      croppedImg = bannerOriginal.replace(/^data:image\/[\w,\d,\W,\D]+;base64,/, "");
	      this.props.setBackground(true)
	    }     
	    this.props.generateBase64(croppedImg, this.props.cropperType);
	    this.props.toggleDialog(); 
  	}
  	
  	render(){
  		const {toggleDialog, isDialogOpen, cropperType, imgSrc} = this.props;
		return(
			<div>
				<Modal isOpen={isDialogOpen} toggle={toggleDialog}>
					<ModalBody className='p-2'  style={{maxHeight:'75vh', overflow:'auto'}}>
						{			
							(cropperType==='banner')
							?
				            <Cropper ref='cropper' src={imgSrc} guides={false} dragMode={'move'} aspectRatio={3/1} viewMode={1} minCropBoxWidth={1200} minCropBoxHeight={400}  />                   
							:
							<Cropper ref='cropper' src={imgSrc}  guides={false} dragMode={'move'} viewMode={1} minCropBoxWidth={50} minCropBoxHeight={50} />
						}
					</ModalBody>
					<ModalFooter>
			            <Button id='crop' color="primary" onClick={this._crop}>Crop</Button>{' '}
			            <Button id='cancel' color="secondary" onClick={toggleDialog}>Cancel</Button>
			        </ModalFooter>
			    </Modal>
		    </div>
	    )
    }
}

export default CropperContainer;

__tests__
import React from 'react';
import {shallow, mount} from 'enzyme';
import toJson from 'enzyme-to-json';
import CropperContainer from '..';

let wrapper;

const toggleDialog = jest.fn();
const generateBase64 = jest.fn();

const props = {
	generateBase64:generateBase64,
	toggleDialog:toggleDialog,
	cropperType:'logo',
	isDialogOpen:true,
	imgSrc:'my base64 url',
}

beforeEach(() => {
	wrapper = mount(<CropperContainer {...props} />)
});

describe('<CropperContainer />', () => {

	it('should render CropperContainer correctly', () => {
		expect(toJson(wrapper)).toMatchSnapshot()
	})	

	it('should called toggleDialog',()=>{
		wrapper.find('Button#cancel').simulate('click');
		expect(props.toggleDialog).toHaveBeenCalled()
	})

	it('should called crop',()=>{
		wrapper.find('Button#crop').simulate('click');
		expect(props.generateBase64).toHaveBeenCalled()
		expect(props.toggleDialog).toHaveBeenCalled()
	})
})

==================Error=====================
Error: Uncaught [TypeError: Cannot read property 'toDataURL' of null]
Actually its console  this.refs.cropper.getCroppedCanvas() to NULL

Please help

**Comment by jrmd** [comment]
@anilljoshi did you find a solution to this?

**Comment by ravipatel07** [comment]
@anilljoshi did you find a solution to this?

**Comment by iaheck** [comment]
that error happens because in your test you don't have everything like a canvas so the method is null. You can mock that method to bypass that (and it makes sense since it's an external library that you're mocking). If you're using jest, you can use [spyOn](https://jestjs.io/docs/jest-object#jestspyonobject-methodname) for that:

```
jest.spyOn(Cropper.prototype, 'getCroppedCanvas').mockImplementation(
      () =>
        ({
          toDataURL: jest.fn(() => 'http://fakeurl.com'),
        } as unknown as HTMLCanvasElement),
    );
```

Now if you're doing more things with that URL you may need to mock those as well
