### ISSUE TITLE
*NOT A BUG*

### ISSUE THREAD

**Issue by akashdeep-sarin** [react-cropper/react-cropper#1081]
Before creating a bug/issue here please check that it is not part of cropperjs and does not exist [in the cropperjs repo](https://github.com/fengyuanchen/cropperjs/issues).

*NOT A BUG*
Why are we doing a 
npm install **--save** react-cropper

and not npm install react-cropper?

TIA for the clarification.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shekhar-shubhendu** [comment]
it is just a suggestion, feel free to use whatever you want.
npm, pnpm, yarn or any other thing.
