### ISSUE TITLE
Make circular/round image

### ISSUE THREAD

**Issue by asmirbelkic** [react-cropper/react-cropper#1095]
Hello,
So i use circular images avatar i'de like to get the image directly crop at the good shape.
Is there any way to make the image circular/rounded please ?
ty

**Comment by shekhar-shubhendu** [comment]
@asmirbelkic You should be able to use this as a guide to implementing the circular crop.
Crop a Round Image: https://github.com/fengyuanchen/cropperjs/blob/main/docs/examples/crop-a-round-image.html

Other Examples: https://github.com/fengyuanchen/cropperjs/tree/main/docs/examples
