### ISSUE TITLE
x,y coordinates of the crop

### ISSUE THREAD

**Issue by riccardolorenzon** [react-cropper/react-cropper#11]
hi, 
is it possible to get the (x,y) coordinates and the width and length of the cropped image related to the original image?

**Comment by roadmanfong** [comment]
Do you mean https://github.com/fengyuanchen/cropper#getdatarounded ?

**Comment by riccardolorenzon** [comment]
yup, thanks!

**Comment by riccardolorenzon** [comment]
hi, 

i can successfully get the coordinates of the cropped image, but only when i actually crop it. 

I noticed that, after having uploaded a new image, a default crop is rendered(looks like it's an cropped image in the center of the main image). I would like to get that cropped image's coordinates as well. 

I tried to get the coordinates immediately after setting the ```src``` property or within the ```componentDidMount``` method, but i always get ```0```(integer's default value in js) for ```x, y, with``` and ```height```. 

Any suggestions?

**Comment by wilz05** [comment]
Hello, 
Is it possible to get the values for x2,y2 
I need to get the values based on the coordinates, since x1 and y2 equal to x and y, in the cropper js results.
I am looking for the results for the below 
  crop=x1,y1,x2,y2
Could you please help me out !

**Comment by Abhyudhey** [comment]
@wilz05 I was also looking for the same. Any luck in getting coordinates in x1, y1, x2, y2 format ?
Some other libraries like imgAreaSelect and JCrop does give coordinates info in x1, y1, x2, y2 format
I was wondering if we can achieve the same using Cropper.

**Comment by wilz05** [comment]
@Abhyudhey 
Yes, once you get x and y 
add width to x and height to y you will be able to get x2 and y2 values 
 
example: 
           X2=  (Math.round(data.x) + Math.round(data.width));
           Y2=  (Math.round(data.y) + Math.round(data.height));

**Comment by Abhyudhey** [comment]
@wilz05 This makes sense. instead of using getData we can use getData([rounded]) then we don't have to explicitly round off x, y, width and height. 
Thanks for the example 👍
