### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading 'current')

### ISSUE THREAD

**Issue by danielr-landhi** [react-cropper/react-cropper#1101]
Hi I have been using de react-cropper for over a while and i never had an issue but it suddenly stopped working, i do not know if it is maybe a version problem or something but that code wasn't changed.

i am having this report: 

`Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'current')

Call Stack
ie
node_modules\react-cropper\dist\react-cropper.es.js (10:7282)
ge
node_modules\react-cropper\dist\react-cropper.es.js (10:11139)
Object.be [as jsx]
node_modules\react-cropper\dist\react-cropper.es.js (10:11848)
eval
node_modules\react-cropper\dist\react-cropper.es.js (10:14890)
d.t [as constructor]
node_modules\preact\compat\dist\compat.module.js (1:1342)
d.O [as render]
node_modules\preact\dist\preact.module.js (1:8145)
j
node_modules\preact\dist\preact.module.js (1:5848)
w
node_modules\preact\dist\preact.module.js (1:2136)
L
node_modules\preact\dist\preact.module.js (1:7328)
j
node_modules\preact\dist\preact.module.js (1:6259)
w
node_modules\preact\dist\preact.module.js (1:2136)
L
node_modules\preact\dist\preact.module.js (1:7328)
j
node_modules\preact\dist\preact.module.js (1:6259)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
L
node_modules\preact\dist\preact.module.js (1:7328)
j
node_modules\preact\dist\preact.module.js (1:6259)
w
node_modules\preact\dist\preact.module.js (1:2136)
L
node_modules\preact\dist\preact.module.js (1:7328)
j
node_modules\preact\dist\preact.module.js (1:6259)
w
node_modules\preact\dist\preact.module.js (1:2136)
L
node_modules\preact\dist\preact.module.js (1:7328)
j
node_modules\preact\dist\preact.module.js (1:6259)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)
w
node_modules\preact\dist\preact.module.js (1:2136)
j
node_modules\preact\dist\preact.module.js (1:5986)`

 "react-cropper": "^2.3.2",
 "cropperjs": "^1.5.13",

**Comment by shekhar-shubhendu** [comment]
Hi @danielr-landhi ,

Can you please submit a [codesandbox](https://codesandbox.io/) repro for this issue 🙏🏾 
And I will take a look into it.

**Comment by silentsakky** [comment]
I am also facing same issue.
Here is codesandbox link https://codesandbox.io/s/confident-tharp-8gkryk?file=/src/demo.js
and here is PR which will fix the issue https://github.com/react-cropper/react-cropper/pull/1105

**Comment by shekhar-shubhendu** [comment]
@silentsakky I've released a new version with for fix.

**Comment by shekhar-shubhendu** [comment]
Closing as this is fixed in 2.3.3
