### ISSUE TITLE
Can you please tell me, how can I change image saving to jpg when I crop it?

### ISSUE THREAD

**Issue by karamjeetiron** [react-cropper/react-cropper#112]
I am using react cropper in my project. Now i need to know that how can i change image saving to jpg when i crop it. For now i am doing it manually but i want to set png to bydefault in code. How can i set it.

Thanks

**Comment by karamjeetiron** [comment]
Still Waiting for reply

**Comment by karamjeetiron** [comment]
Any suggestions?

**Comment by JianFengH** [comment]
@karamjeetiron  You can look up here [cropper.getCroppedCanvas().toDataURL('image/jpeg')](https://github.com/fengyuanchen/cropperjs#known-issues)
