### ISSUE TITLE
Allow file objects as a source

### ISSUE THREAD

**Issue by NyakoFox** [react-cropper/react-cropper#1140]
**Is your feature request related to a problem? Please describe.**
When you upload a file using `<input>`, it gives you a File object, however this requires a URL.

**Describe the solution you'd like**
Being able to input a File object as the `src` would be nice.

**Describe alternatives you've considered**
I've considered converting the File object to a URL, but that could cause memory leaks.

**Additional context**
None.

**Comment by shekhar-shubhendu** [comment]
This can be done as seen in this demo (also in the readme)
https://codesandbox.io/s/wonderful-pine-i7fs3?file=/src/Demo.tsx
