### ISSUE TITLE
Problem getting the example to work with a local image file

### ISSUE THREAD

**Issue by simax** [react-cropper/react-cropper#12]
I'm having a problem getting the example to work with a local image file.

When I run the hosted example  at `http://roadmanfong.github.io/react-cropper/example/` everything works fine, even when choosing a local `jpg` file. But when I try to use react-cropper in my own app **and choose a local jpg**, or run the example from the repo **and choose a local jpg**, I get the following error: 

`Uncaught TypeError: this.refs.cropper.getCroppedCanvas(...).toDataURL is not a function`

Its fine with the default image 

In order to debug I changed the the `_crop` function as follows 

```
  _crop(){
    var imageCropper = this.refs.cropper.getCroppedCanvas()  
    this.setState({
      preview: imageCropper.toDataURL()
    });
  }
```

When using the default image, `imageCropper` is a `canvas` type. When I select a **local .jpg file** the `imageCropper` object becomes a `jquery` object and the error occurs.

Any idea what's wrong?

**Comment by favorit** [comment]
I did change version for Cropper in ```package.json``` to
```
"dependencies": {
  "cropper": "0.11.0"
},
```
and example works well.

So we need figure out why it does not work with newest versions of cropper: ```0.11.1``` and ```1.0.0-rc.1```

**Comment by simax** [comment]
Thanks, using version "0.11.0" removed that problem. The other bigger problem is performance when previewing. Looking at the examples here http://fengyuanchen.github.io/cropper/#examples. of the jquery cropper plugin, they're blazingly fast and smooth, even with large images. The react version is slow and "laggy" with larger images. Anything that can be done that?

**Comment by roadmanfong** [comment]
I'm not sure what is going on in first question. I'll look into it later.

About the second question.
That because I didn't write example like http://fengyuanchen.github.io/cropper/#examples.
It uses API https://github.com/fengyuanchen/cropper#preview, but I use https://github.com/fengyuanchen/cropper#getcroppedcanvasoptions to get canvas and get dataUrl  and than render it to image.

It is possilbe to rewrite example like http://fengyuanchen.github.io/cropper/#examples.

**Comment by simax** [comment]
@roadmanfong thanks, would it be possible to show what I would need to put in the _crop method to use the preview property <ReactCropper preview .... /> like the examples on the jquery plugin?

**Comment by bardt** [comment]
I have the same problem, not only with local example, but with remote `src` as well. Looks like there is an issue with `replace` method, but not sure.

@roadmanfong Can I somehow help you solving this issue?

**Comment by riccardolorenzon** [comment]
I have the same problem too, the cropper version in the ```package.json``` should be set 0.11.0 until this bug is not fixed.
