### ISSUE TITLE
Outdated refs example

### ISSUE THREAD

**Issue by DanielRuf** [react-cropper/react-cropper#126]
> ref={cropper}

This does not work in specific cases. It should be set in the constructor of the class.

**Comment by DanielRuf** [comment]
> Also no example of how to set up using React.useRef instead of React.createRef

This is a general usecase and not specific. My issue is about the outdated example in the docs / readme.

**Comment by frisi** [comment]
i'll link the pr of @DanielRuf here for completeness: https://github.com/roadmanfong/react-cropper/pull/128/

however, this does not resolve the problem that the current props interface is not compatible with `useRef` hook. (https://github.com/roadmanfong/react-cropper/issues/134)
iiuc this is why `ReactCropper` can't be used in functional components
