### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by EwanValentine** [react-cropper/react-cropper#13]
Including 'react-cropper' causes an unexpected token error, I'm using ES6 so:
 `import Cropper from 'react-cropper';` is the offending code.

**Comment by roadmanfong** [comment]
I'm using ES6 too, but I didn't have that kind of issue. 
`import Cropper from 'react-cropper';` works in my code
What's did your log say?

**Comment by EwanValentine** [comment]
Basically gulp won't transpile whilst I have `import Cropper from 'react-croppper'` in my ES6 code

`[10:15:35] gulp-notify: [Compile Error] Unexpected token`

**Comment by roadmanfong** [comment]
I think maybe the problem is the configuration of gulp.
Maybe you can try other library such as `import jquery from 'jquery'` to make sure that `import` is valid  token in your gulp configuration.

https://babeljs.io/docs/setup/#gulp

**Comment by EwanValentine** [comment]
I'm using loads of other import statements, it's quite a big project. I've noticed the main file in the library is already transpiled to ES5, so maybe my set-up's attempting to re-transpile it? I'm not sure

**Comment by DDChiang** [comment]
Stack: es5 + gulp

I also got an "unexpected error" token just from requiring the 'react-cropper' module. 

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    SyntaxError: Unexpected token


Not sure what's happening. I'm not even calling or rendering the component in a React.createClass statement.

**Comment by r31gN** [comment]
+1 to this issue happening

**Comment by utkuturunc** [comment]
This was happening in my isomorphic app. The workaround was to put the require line inside an if-browser conditional.
