### ISSUE TITLE
Ref is requiring string which is strange

### ISSUE THREAD

**Issue by chhinsras** [react-cropper/react-cropper#134]
TypeScript error in E:/ASP.NET C#/Projects/reactivities/client-app/src/app/common/photoUpload/PhotoWidgetCropper.tsx(28,7):
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ReactCropperProps>): ReactCropper', gave the following error.
    Type 'RefObject<ReactCropper>' is not assignable to type 'string | (string & RefObject<Cropper>) | (string & ((cropper: ReactCropper | null) => any)) | (RefObject<ReactCropper> & string) | (RefObject<ReactCropper> & RefObject<Cropper>) | ... 4 more ... | undefined'.
      Type 'RefObject<ReactCropper>' is not assignable to type '((instance: ReactCropper | null) => void) & RefObject<Cropper>'.
        Type 'RefObject<ReactCropper>' is not assignable to type '(instance: ReactCropper | null) => void'.
          Type 'RefObject<ReactCropper>' provides no match for the signature '(instance: ReactCropper | null): void'.
  Overload 2 of 2, '(props: ReactCropperProps, context?: any): ReactCropper', gave the following error.
    Type 'RefObject<ReactCropper>' is not assignable to type 'string | (string & RefObject<Cropper>) | (string & ((cropper: ReactCropper | null) => any)) | (RefObject<ReactCropper> & string) | (RefObject<ReactCropper> & RefObject<Cropper>) | ... 4 more ... | undefined'.
      Type 'RefObject<ReactCropper>' is not assignable to type '((instance: ReactCropper | null) => void) & RefObject<Cropper>'.
        Type 'RefObject<ReactCropper>' is not assignable to type '(instance: ReactCropper | null) => void'.  TS2769

    26 |   return (
    27 |     <Cropper
  > 28 |       ref={cropper}
       |       ^
    29 |       src={imagePreview}
    30 |       style={{ height: 200, width: "100%" }}
    31 |       // Cropper.js options``

**Comment by frisi** [comment]
same here.
if i understand correctly - the current type definition of `ReactCropperProps` is not compatible with `useRef` hook.

**Comment by frisi** [comment]
adding ` React.RefObject<Cropper | undefined>` to the `ref` in @types/react-cropper/index.d.ts would fix that:

```typescript
export interface ReactCropperProps extends Cropper.Options, Omit<React.HTMLProps<HTMLImageElement>, 'data' | 'ref'> {
    ref?: string | React.RefObject<Cropper | undefined> | ((cropper: null | ReactCropper) => any);
}
```

the ref can be initialized and used this way:
```typescript
const cropper = useRef<Cropper | null>(null)

cropper.current?.getData(true)
```
