### ISSUE TITLE
import 'cropperjs/dist/cropper.css' using css module

### ISSUE THREAD

**Issue by anitta-paul** [react-cropper/react-cropper#136]
I am using css module for my entire project. Simply writing `import 'cropperjs/dist/cropper.css'` is not loading the style. Is it because I use css module in my project? if Yes, How can I use css module to import the `cropper.css`?

**Comment by DraconView** [comment]
Just in case someone else happens, I was missing the css file, I looked for it from another project and also how I use pnpm to rename the folders, I solved it with that
