### ISSUE TITLE
Scale (X & Y) doesn't work properly

### ISSUE THREAD

**Issue by hadiranjbar25** [react-cropper/react-cropper#138]
I have a custom button like this:
`<button onClick={() => this.cropper.current.scaleX(-1)}></button>`

When I click on the button it works, but when I click on it again, nothing happens!
Is it a bug or I should do it in another way?

**Comment by afkinc** [comment]
You need to store the current value of scaleX (-1 or 1) in a variable or state:
```
let scaleX = 1;
<button onClick={() => { scaleX*=-1; this.cropper.current.scaleX(scaleX)}}></button>
```
