### ISSUE TITLE
Issue trying to load an HEIC file on a non iOS device

### ISSUE THREAD

**Issue by andrewrutter** [react-cropper/react-cropper#141]
We have a project where users need to crop images and may have copied them to a laptop. As a result, we need to try and load HEIC images into a <Cropper> instance but this does not seem to be working.  The canvas is not created and in the DOM we actual see an <img> tag with that HEIC file content as a url.

To reproduce:

1. Read a file from disk on a non iOS device using FileReader
2. Call reader.readAsDataURL() to get the file content
3. Instantate a new cropper element passing in the reader.result as the file source

Expected behavior that the image file will display in the cropper canvas as is the case for all other filetypes. No canvas element is created

**Comment by sd2894** [comment]
I also had a same problem did you get any solution for this

**Comment by haripermadi** [comment]
is there any solution?
