### ISSUE TITLE
Cropper fetches the same image twice

### ISSUE THREAD

**Issue by dhruvk03** [react-cropper/react-cropper#146]
Cropper fetches the same image twice:
1. When it loads the image through XHR.
2. For the image tag `<img src="image-url" alt="picture" class="cropper-hidden" style="opacity: 0;">`

I am not sure why this extra `img` tag added to the DOM, as it doesn't seem to be doing anything. Even if that `img` tag is required, it should use the image already fetched by XHR call which `cropper.js` makes. Adding extra network call for the same image negatively impacts load times, especially when the image is large.

**Comment by moroz** [comment]
Has anyone come up with a solution by now? Could we do it in such a way that we put the <img> tag as a child of the cropper and then initialize the widget on that element?

**Comment by shekhar-shubhendu** [comment]
@moroz what @dhruvk03 had proposed earlier is not not how cropperjs works. You need to create a img tag and provide the reference of the same to cropper.
Also, this issue has nothing to do with react-cropper.

Take a look [here](https://github.com/fengyuanchen/cropperjs/issues/671). Most probably this will resolve your issue.
