### ISSUE TITLE
Refactor Proposal

### ISSUE THREAD

**Issue by shekhar-shubhendu** [react-cropper/react-cropper#149]
I am thinking to refactor this library so to include below things

- [x] Update cropper.js version
- [x] use Typescript
- [x] Convert to a functional component
- [ ] add unit tests
- [x] update documentation
- [ ] Provide Hooks for easy usage

Things would be more or less in the above order and therefore I would like to ask the people using it if this is something they would like to have.

**Comment by hisnameisjimmy** [comment]
Actually really pumped to see this, do you think 'develop' is far enough along that I could start using it without regretting it?

**Comment by shekhar-shubhendu** [comment]
If you want you can try using the branch now.
I am occupied a lot these days. If I find I'll make a preview/beta release so we can properly test it.
I'll also need to find some time to add unit tests

**Comment by shekhar-shubhendu** [comment]
@hisnameisjimmy if you can try out this and provide some feedback then I would be really thankful
https://www.npmjs.com/package/react-cropper/v/2.0.0-0

**Comment by shekhar-shubhendu** [comment]
Closing this for now. Will try to make a proper 2.0.0 release soon.
