### ISSUE TITLE
Something wrong with cropper in Chrome 84.0.4147.105

### ISSUE THREAD

**Issue by Lkrm** [react-cropper/react-cropper#199]
cropper view doesn`t work correctly (Can not change cropperd area)

**Comment by shekhar-shubhendu** [comment]
Please provide react-cropper version and a screenshot.
Also, I suggest checking on the cropperjs repo regarding this.

**Comment by shekhar-shubhendu** [comment]
I got the chrome update today and with version 2.0.0-0
it seems to be working https://codesandbox.io/s/react-cropper-demo-xppqu

**Comment by shekhar-shubhendu** [comment]
Since there was no reply. I am closing this for housekeeping purposes. Please comment below if this needs to be discussed here.
