### ISSUE TITLE
Cropper with preview broke without updates (1.3.0)

### ISSUE THREAD

**Issue by hronnro** [react-cropper/react-cropper#223]
**Describe the bug**
I've been using react-cropper on my website for a few months and it has always worked flawlessly until sometime in the past 20 days when something broke and now the cropper is behaving weirdly (see GIF). 

I'm using version 1.3.0 of react-cropper and I've verified that this happens both on Chrome(v.84.0.4147.105) and on Safari(v.13.1.1 )

**The issue:** A copy of the image always shows in the background that should not be visible, and when the image is scaled it will reposition itself which is not expected.

A person on our team that uses the cropping tool has verified that it worked as expected 21 days ago, but when she opened it today it was broken. We have not done any changes to the code during that time, nor updated any dependencies. 

**Screenshots**
![cropper](https://user-images.githubusercontent.com/7429825/89538311-ed7d8700-d7e9-11ea-8f73-2d95adf39ea6.gif)

**Comment by shekhar-shubhendu** [comment]
@hronnro Thanks for opening the issue here and providing a detailed description of the issue.

But seems like a issue associated with cropperjs.
I think if you open the issue there then you might be able to find a quicker solution to your problem.

If possible, please try to repro and post a codesandbox of your issue and I'll try to take a look too.

**Comment by hronnro** [comment]
I've figured what caused the bug - this website is running a few different tools along with the cropper tool, and a .css file for one of the tools was updated with 
```
img {
...
}
```
that updated all img properties globally, which affected the cropper..


Sorry for not digging deeper before reporting, and thanks for your help! 🙏

**Comment by shekhar-shubhendu** [comment]
Thanks for posting the clarification.
