### ISSUE TITLE
Initial Aspect Ratio is not respected in 2.0.0

### ISSUE THREAD

**Issue by kikoanis** [react-cropper/react-cropper#248]
Before creating a bug/issue here please check that it is not part of cropperjs and does not exist [in the cropperjs repo](https://github.com/fengyuanchen/cropperjs/issues).

**Describe the bug**
The aspect ratio is not respected. This only happened after the introduction of `initialAspectRatio`, v. 2.0.0 
**To Reproduce**
1. Go to https://codesandbox.io/s/react-cropper-demo-forked-p6hrg?file=/index.js
2. The initial aspect ratio is set to 16:9. Try to resize the crop area and notice it is not respected

**Expected behavior**
On resizing the crop area, the initial aspect ratio should be respected.

**Desktop (please complete the following information):**
 - OS: Windows and iOS
 - Browser: All Browsers; Chrome, FireFox, Edge.
 - Version: 2.0.0

**Comment by kikoanis** [comment]
Looking further into the introduction of `initialAspectRatio`, I don't see where this is used. I think it should be mapped to `aspectRatio` to be passed into cropperjs. Otherwise, it is useless really. 
Final notice, if I add the original `aspectRatio` to the props it works fine which defeats the whole idea of `initialAspectRatio` unless I am missing something.

**Comment by shekhar-shubhendu** [comment]
@kikoanis if you check [here](https://github.com/fengyuanchen/cropperjs#initialaspectratio) you'll see that `initialAspectRatio` is a cropperjs prop and is passed as is to the cropperjs. If it is not working as expected then react-cropper can not do anything.

**Comment by kikoanis** [comment]
@shekhar-shubhendu  alright, that is what I was missing. Makes sense. I thought this would resolve to the other aspect ratio. Will resolve the issue. thanks for getting back to me.
