### ISSUE TITLE
function passed to crop prop doesn't get updated cropper instance

### ISSUE THREAD

**Issue by duc-talentwunder** [react-cropper/react-cropper#254]
I'm not sure if I'm doing something wrong here.
On `crop` I need to read the width and height. With previous version <2.0 with `ref` it worked by calling `getCropBoxData`. Now I can't get the instance in the function passed to crop anymore.

I've prepared a very small codesandbox to state my issue:
https://codesandbox.io/s/zealous-firefly-f2bqc?file=/src/App.js

Can you please have a look at line 11 in App.js?

**Comment by shekhar-shubhendu** [comment]
I checked the sandbox and it looks like that the instance returned is undefined.
I will try to check what is the reason behind this.

**Comment by shekhar-shubhendu** [comment]
on looking further it seems like cropper is properly initialized 

![image](https://user-images.githubusercontent.com/9253059/90516299-13991480-e164-11ea-965a-f5f1a554cd26.png)

and is even set in the state
![image](https://user-images.githubusercontent.com/9253059/90516386-33c8d380-e164-11ea-95d2-f96b4de2836d.png)

**Comment by duc-talentwunder** [comment]
> on looking further it seems like cropper is properly initialized
> 
> ![image](https://user-images.githubusercontent.com/9253059/90516299-13991480-e164-11ea-965a-f5f1a554cd26.png)
> 
> and is even set in the state
> ![image](https://user-images.githubusercontent.com/9253059/90516386-33c8d380-e164-11ea-95d2-f96b4de2836d.png)

yes, to me it seems that the passed function to the `crop` prop gets the function initially with the initial state value but then doesnt get updated. maybe you need to check for `crop` reference update and rerender?

**Comment by duc-talentwunder** [comment]
I've extended the codesandbox to show what I mean:
https://codesandbox.io/s/zealous-firefly-f2bqc?file=/src/App.js

you see that the `onClick` listener of the `div` element is working as expected. I would expect the `crop` to behave the same way or am I missing on something?

**Comment by shekhar-shubhendu** [comment]
I'll take a look. Thanks for pointing this out.

**Comment by shekhar-shubhendu** [comment]
@duc-talentwunder How `onClick` on div works and how `crop` event is handled by the cropperjs is completely different. and re-rendering on basis of `crop` prop is not a good idea.
What will work here is that I again enable the `ref` and we use the copper from there.

**Comment by duc-talentwunder** [comment]
alright, sorry for the inconvenience and thanks a lot for creating this PR so fast. Can you already tell, when the next release including this workaround will be?

**Comment by shekhar-shubhendu** [comment]
@duc-talentwunder I will try to do this by this weekend but can not be sure. Let me know if you find any other issues.

**Comment by duc-talentwunder** [comment]
alright thanks a lot! i'll let you know if anything occurs

**Comment by blacksmoke26** [comment]
Any fix here?

**Comment by blacksmoke26** [comment]
![image](https://user-images.githubusercontent.com/425744/90769971-880db800-e30a-11ea-8ed7-915303e47c2f.png)

Same error here: cropper is undefined!

**Comment by shekhar-shubhendu** [comment]
fix is applied and merged and will be part of the next release.

**Comment by shekhar-shubhendu** [comment]
@blacksmoke26 @duc-talentwunder check the new release
