### ISSUE TITLE
autoCropArea={1} does not work

### ISSUE THREAD

**Issue by pentyh** [react-cropper/react-cropper#255]
version: 2.0.0 autoCropArea={1}  is not work
the src image view on natural size ...

**Comment by shekhar-shubhendu** [comment]
Please provide more details and if possible a codesandbox repro.

**Comment by pentyh** [comment]
https://codesandbox.io/s/rough-voice-c752q?file=/src/Demo.tsx

you may change the depended react-cropper version from 2.0.0 to 1.3.0
you will find the diff 

version 1.3.0 autoCropArea option is work correct

**Comment by shekhar-shubhendu** [comment]
what seems to be 'causing the difference is the CSS property that was introduced

```js
max-width: 100%
```

it is recommended here in cropperjs: https://github.com/fengyuanchen/cropperjs#example
please check this PR: https://github.com/react-cropper/react-cropper/pull/153

as far as autoCropArea property is related it seems to work and it is a cropperjs prop and as is passed as is.

**Comment by shekhar-shubhendu** [comment]
closing this for housekeeping purposes. if you have any question feel free to comment below.
