### ISSUE TITLE
Property 'ref' does not exist on type 'IntrinsicAttributes & ReactCropperProps & { children?: ReactNode; }'.

### ISSUE THREAD

**Issue by summer996** [react-cropper/react-cropper#258]
Before creating a bug/issue here please check that it is not part of cropperjs and does not exist [in the cropperjs repo](https://github.com/fengyuanchen/cropperjs/issues).

**Describe the bug**
dependencies info:
react-cropper: 2.0.0
@types/react-cropper: 1.3.0

bug: 
Property 'ref' does not exist on type 'IntrinsicAttributes & ReactCropperProps & { children?: ReactNode; }'.

code:

import React, { useEffect, useState, useRef } from 'react';
import Cropper from 'react-cropper';
import 'cropperjs/dist/cropper.css';

const ReviewWatermarkPage = (props: any) => {
    const [src, setSrc] = useState('./test.jpg');
    const cropperRef = useRef<Cropper | undefined>(null);
    return (
        <Cropper
            src={src}
            ref={cropperRef}
            viewMode={1}
            zoomable={false}
            aspectRatio={1} // 固定为1:1  可以自己设置比例, 默认情况为自由比例
            guides={false}
            cropend={() => {
                console.log(cropperRef.current.getCroppedCanvas());
            }}
        />
    );
};

**Comment by shekhar-shubhendu** [comment]
Please remove @types/react-cropper package
ref has been removed in 2.0.0
But it might come back in the next release

**Comment by summer996** [comment]
I want to use ref, which version of @types/react-cropper package can be selected

**Comment by shekhar-shubhendu** [comment]
To stay with ref you have to use react-cropper 1.3.0 with the types package untill the next release is out. At that point you can remove the types package and use the latest release

**Comment by shekhar-shubhendu** [comment]
closing this for housekeeping purposes. if you have any question feel free to comment below.

**Comment by summer996** [comment]
thank you i solved;

**Comment by shekhar-shubhendu** [comment]
@summer996  i guess you can test the 2.1.0 now as it will have ref support

**Comment by summer996** [comment]
emmm, i had try,but failed,which version of react-cropper is 2.1.0，and  @types/react-cropper  is  1.3.0,   
i use other way to solved,  
but also thanks
