### ISSUE TITLE
onInitialized() isn't called and img opacity set to 0

### ISSUE THREAD

**Issue by zeekrey** [react-cropper/react-cropper#266]
**Describe the bug**
The img-node within Cropper has the opacity set to 0 and the onInitialized() method is not called.

**To Reproduce**
Unfortunately I'm not able to reproduce the issue in a codesandbox. I just copied the example from the codesandbox example.

**Expected behavior**
The onInitialized() method should be called.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by JaylanChen** [comment]
same bug.

react-cropper   v2.1.0

[bug demo](https://codesandbox.io/s/inspiring-johnson-mkcen)

Modified react-cropper version based on your example (2.0.0 → 2.1.0)

**Comment by shekhar-shubhendu** [comment]
This is a known thing.
To fix you can either pass the ref to react-cropper or use V2.1.1-0
