### ISSUE TITLE
[v2.1.0] react-cropper not rendering when ref not passed

### ISSUE THREAD

**Issue by duc-gp** [react-cropper/react-cropper#267]
Hi again,

I just tried out the new version and somehow something seems not to work as expected anymore with the `src` prop

here its working version: 2.0.0:
https://codesandbox.io/s/cropper-second-bug-working-bcqp5?file=/src/App.js

here same code not working 2.1.0:
https://codesandbox.io/s/cropper-second-bug-not-working-seu0e

code is the same, only difference is version number

**Comment by duc-talentwunder** [comment]
thats great, thanks!

**Comment by duc-talentwunder** [comment]
I checked out your codesandbox and just wanted to test but am confused now. In your example you just created a ref and passed it to the cropper component, but how would I get the instance now?

we have the following in our codebase, this code worked in version 1.3
```
ref={ref => {
    this.cropper = ref;
}}
```
but with version 2.1.0 and this code we get `The first argument is required and must be an <img> or <canvas> element.`

**Comment by shekhar-shubhendu** [comment]
I think I fixed this too in V2.1.1-0

**Comment by duc-talentwunder** [comment]
alright thanks, ill check it out onced its released
