### ISSUE TITLE
react-cropper not rendering image when viewMode and zoomTo both are set to 0

### ISSUE THREAD

**Issue by Chetnatl** [react-cropper/react-cropper#287]
I was using react-cropper with version 2.0.0. It was working properly. but when I updated it with the latest version(2.1.0). It is showing me a blank image after selecting an image and no crop functionality is applying on it.

You see the below screenshot:
**using 2.0.0**
![image](https://user-images.githubusercontent.com/61341696/91426215-d32f4a00-e879-11ea-9cd1-d630ca5faae3.png)

**using 2.1.0**
![image](https://user-images.githubusercontent.com/61341696/91423282-f8ba5480-e875-11ea-84a2-bcd667277d3d.png)

I need immediate the solution to this issue because I'm using this into my project.

**Comment by aabc6419tw** [comment]
Have the same problem！！！

**Comment by shekhar-shubhendu** [comment]
@shekhar-shubhendu if you need an immediate fix for this then it is available in v2.1.1-0.

**Comment by Chetnatl** [comment]
@shekhar-shubhendu this is not duplicate of #267. When I pass ref. it is giving me an error.

**Comment by alabobriggs** [comment]
having same issue

**Comment by shekhar-shubhendu** [comment]
@Chetnatl then please provide a repro for this and also did you try using v2.1.1-0 what is the issue you are facing using that?

**Comment by Chetnatl** [comment]
When I use v2.1.1-0

**Comment by alabobriggs** [comment]
Fixed issue by upgrading to 2.1.1-0

**Comment by shekhar-shubhendu** [comment]
@Chetnatl I think I found the issue you are facing.
In one of the PRs, a community member changed the default value of `zoomTo` from `1` to `0`. It was to fix another issue. For more info, please take a look here #268.
And the above change seems to be 'causing the issue if the `viewMode` is set to `0` which is cropperjs default.

For now, to make the image render inside the cropper either set the `zoomTo` prop or `viewMode` to any value except `0`.

I'll try to investigate further on this in my free time.
thanks :)

**Comment by shekhar-shubhendu** [comment]
closing as this should be resolved with v2.1.2
