### ISSUE TITLE
React-Cropper does not render image in full height/width when data is set

### ISSUE THREAD

**Issue by kikoanis** [react-cropper/react-cropper#302]
Please check this link for how to reproduce. If you set the data object (for copping area), the image won't be displayed correctly until you resize window or exclude data object.

https://codesandbox.io/s/amazing-driscoll-dj9y8?file=/src/Demo.tsx (This will show the image incorrectly for a split of a second then it maximizes it due to code sandbox rerendering)
https://dj9y8.csb.app/  (This will display the image incorrectly)

**Comment by shekhar-shubhendu** [comment]
@kikoanis I see multiple instances of same issue in being reported in cropperjs repo. According to the maintainer there, you need to call the setCropBoxData method. Maybe search there and you might be able to find what you are looking for.

**Comment by kikoanis** [comment]
will do, thanks for your response. Yeah I should've looked there first as most of the issues reported here are originated in the CropperJs library.

**Comment by kikoanis** [comment]
For any future search, it turned out, changing the `viewMode`  to 2 should do the trick
