### ISSUE TITLE
Cropper instance is undefined in crop function

### ISSUE THREAD

**Issue by lisa-tw** [react-cropper/react-cropper#305]
**Describe the bug**
I can not retrieve the cropper instance in the crop function to get width and height of the crop box. Would be great if you checked the sandbox and let me know if I am doing something wrong or if this is a bug.

**To Reproduce**
https://codesandbox.io/s/nervous-bassi-8bv55

Cropper instance in the crop function is undefined

**Expected behavior**
Cropper instance in the crop function should be defined

**Desktop:**
 - OS: OSX 10.15.6
 - Browser: Chrome
 - Version 2.1.1

**Comment by shekhar-shubhendu** [comment]
Use the ref for this.
also, the crop is not a method but an event in cropperjs.
this is what you want to do I believe https://codesandbox.io/s/nostalgic-forest-gyxek?file=/src/App.js

closing as this was already reported earlier and hence ref was reintroduced.

**Comment by lisa-tw** [comment]
Thanks for your quick reply - working now.
