### ISSUE TITLE
移动端能否支持toggleDragModeOnDblclick

### ISSUE THREAD

**Issue by luoying1** [react-cropper/react-cropper#365]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shekhar-shubhendu** [comment]
@luoying1 since this is a wrapper component we will not be able to add this feature directly.
If cropperjs supports this then we can enable it on react-cropper side too. Please open this feature request in cropperjs repo.
