### ISSUE TITLE
`crop` shouldn't be considered as unchangeable 

### ISSUE THREAD

**Issue by cjke** [react-cropper/react-cropper#39]
It would be ideal if `crop` wasn't considered unchangeable as it makes it impossible to pass arguments with the callback. 

In the following example, I have multiple croppers in a loop, and need to pass the item or index in with the callback crop. But this counts as a different function each time. 

Handling it refs alone become messy with a series of items. 

```
<div>
    { map(items, item => (
        <Cropper
            className="Uploader__cropper"
            src={item.original}
            style={{height: 400, width: '100%'}}
            aspectRatio={16 / 9}
            checkCrossOrigin={false}
            background={false}
            guides={true}
            crop={(e) => this.onCrop(e, item)} />
        />
    ))}
</div>
```

**Comment by PGDJ** [comment]
+1 did you find a solution for this?
