### ISSUE TITLE
Passing some props which are not resulting in visible change

### ISSUE THREAD

**Issue by realisation** [react-cropper/react-cropper#41]
I'm trying to animate a canvas to be a certain size, as well as the cropbox, by using the props `canvasData` and `cropBoxData`. But when I load the page and finally get the image into the cropper (after it's uploaded to a server), neither of values I put in these two props are having any effect. Also I am passing `dragMode`, which does not appear to do anything -- at least on a Macbook Pro.

There are other props that do work such as the aspect ratio, and disabling zooming. 

The source for the cropper is set to a property of the state which is not always populated. 

Wrapped in a div in the render function is my cropper component: 

```
        <Cropper
          ref="cropper"
          dragMode="none"
          src={this.state.file.preview}
          style={this.cropperStyles}
          aspectRatio={16 / 5}
          cropBoxData={{left:0, top:0, width:50, height:50}}
          canvasData={{left:0, top:0, width: 500, height: 300 }}
          crop={this._crop.bind(this)}>
        </Cropper>
```

Here are the functions that alter the data in the cropper. When I call _setCanvasData, then those functions work. But not when passed as props. 

```
  onFinishS3Put = (public_url, file) => {

    this.setState({
      file: file
    });

  }

  _setCanvasData = () =>{

    this.refs.cropper.setCropBoxData({top:0, left:0, width:50, height: 50});
    this.refs.cropper.setCanvasData({top: 0, left: 0, width: 500 , height: 300 });
    this.cropper.scale(1,-1);

  }
```

**Comment by amitava82** [comment]
This is still an issue. If I update a prop such as `viewMode` in the component prop, it does not update. Even after calling `setCropBoxData` I do not see any change.

**Comment by Mohamed-Ibrahim-01** [comment]
I have the same issue, even using `setCropBoxData` or `cropBoxData` prop nothing changes
