### ISSUE TITLE
Export Cropper types (the one in cropperjs)

### ISSUE THREAD

**Issue by yououhan123** [react-cropper/react-cropper#412]
**Is your feature request related to a problem? Please describe.**
I couldn't type my ref correctly. Specifically Cropper type can be found correctly when building the files but I got type errors in the built files e.g. MyComponent.d.ts because it doesn't know where to find the "Cropper" type

**Describe the solution you'd like**
Cropper type (from cropperjs) is exported from types/index.d.ts.

**Comment by shekhar-shubhendu** [comment]
Hi @yououhan123 
Thanks for the PR.
But I do not understand why a re-export from react-cropper is required.
and what type of `ref` are you trying to pass to the react-cropper.
