### ISSUE TITLE
在2.1.4版本中当动态设置dragMode属性时，dragMode设置无效

### ISSUE THREAD

**Issue by smz8023** [react-cropper/react-cropper#416]
<Cropper
            ref={ref}
            viewMode={1}
            autoCrop={false}
            dragMode={toggleBoxcree ? "crop" : "move"}// 动态设置时，不生效只有初始化生效
            cropend={cropend}
            className="croppers"
            style={{ height: "100%", width: "100%" }}

**Comment by shekhar-shubhendu** [comment]
@smz8023 
Thanks for reporting this.
It would be super nice if you can provide a codesandbox for this.
else it might take some time for me to confirm and fix this.

**Comment by shekhar-shubhendu** [comment]
I was able to repro this here and will try to add a fix for this
https://codesandbox.io/s/react-cropper-demo-forked-oi0e8?file=/src/Demo.tsx:1588-1596

**Comment by shekhar-shubhendu** [comment]
after checking again, it seems you should call [setDragMode](https://github.com/fengyuanchen/cropperjs#setdragmodemode) instead and re-rendering the entire cropper would not be ideal.

I can add a check for this inside react-cropper too but this will invite extra complexity and code as then I'll have to add the same check for all the options and call their respective setter methods.
