### ISSUE TITLE
Cropping a GIF image

### ISSUE THREAD

**Issue by kafinsalim** [react-cropper/react-cropper#442]
Try to crop a gif in the example here https://codesandbox.io/s/wonderful-pine-i7fs3?file=/src/index.tsx
the preview had no problem (the gif image is moving), but after cropping and download the final image. The gif image is not moving anymore. The final image is the first frame of the gif in cropped size.

Is there any configuration to enable gif cropping or is it not supported?

**Comment by shekhar-shubhendu** [comment]
@kafinsalim AFAIK cropperjs does not work with gifs
You should check the cropperjs documentation and see if it supports that.

**Comment by STDSuperman** [comment]
> Try to crop a gif in the example here https://codesandbox.io/s/wonderful-pine-i7fs3?file=/src/index.tsx the preview had no problem (the gif image is moving), but after cropping and download the final image. The gif image is not moving anymore. The final image is the first frame of the gif in cropped size.
> 
> Is there any configuration to enable gif cropping or is it not supported?

Maybe you can use this package to crop gif with cropperjs: [super-image-cropper](https://github.com/STDSuperman/super-image-cropper).
