### ISSUE TITLE
Consider using useLayoutEffect instead of useEffect, useRef instead of useState in ReactCropper component.

### ISSUE THREAD

**Issue by jamespedid** [react-cropper/react-cropper#447]
**Is your feature request related to a problem? Please describe.**
I've run into some odd infinite loops when calling the crop event. I think that this can be traced down to the usage of various useEffect and useState calls.

**Describe the solution you'd like**
I think it would be beneficial to use useLayoutEffect instead of useEffect when setting up the cropper element. I don't see why it should be asynchronous when the component isn't intended to function until the cropper is initialized.

Additionally, the cropper reference itself should use useRef instead of setState. The component probably doesn't need to rerender when the cropper is initialized, so using setState here seems inappropriate.

**Describe alternatives you've considered**
I had to implement my own cropper from cropperjs instead of using the library because of this. I was seeing some very odd side effects with regards to crop and calling setData on the cropper that aren't present in an implementation that uses the two above features. 

**Additional context**
I'm unsure of use cases where useEffect would be applicable. Evaluate carefully and see if the implementation above is superior or not.

**Comment by shekhar-shubhendu** [comment]
Thanks. I will try to evaluate and see how I can improve it
