### ISSUE TITLE
there are a lot of react warnings

### ISSUE THREAD

**Issue by lqzerogg** [react-cropper/react-cropper#45]
here are one of them.
warning.js?7533:36 Warning: You are manually calling a React.PropTypes validation function for the `zoomOnTouch` prop on `ReactCropper`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

please fix this issue. thank you

**Comment by sabatsu** [comment]
+1
