### ISSUE TITLE
How to make it work with react-dropzone?

### ISSUE THREAD

**Issue by jasan-s** [react-cropper/react-cropper#46]

**Comment by mrChex** [comment]
1) `<Dropzone onDrop={this.onDrop} style={styles} accept="image/*" multiple={false}>`
2) `onDrop = (acceptedFiles) => {
        const file = acceptedFiles[0];
        this.setState({file});
    };`
3) `<Cropper
                ref='cropper'
                src={this.state.file.preview}` />

**Comment by nmynarcik** [comment]
@jasan-s I found this very helpful when doing the same thing. http://www.sketchpad-media.com/docs/how-to/reactjs-dropzone-cropping-tool-laravel-backend/

**Comment by boriswexler** [comment]
I am actually trying to get it to work with https://github.com/felixrieseberg/React-Dropzone-Component
Anyone had any luck? I've been trying for a while now, but can't seem to extract a url that can be passed as source to react-cropper from the File object returned by the dropzone. Thanks!

**Comment by nmynarcik** [comment]
I started down that path too @boriswexler and then had to ditch it and go with the way I posted above. Good luck!

**Comment by spoeck** [comment]
Here is an very simple example:
```javascript
import {StyleSheet, Text, View} from "react-primitives";

import Cropper from 'react-cropper';
import 'cropperjs/dist/cropper.css';
import Dropzone from "react-dropzone";


class DealEditorPage extends Component {

    constructor() {
        super();

        this.state = {
            image: null,
        };
    }


    render() {

        return (
            <View style={styles.container}>
                <Dropzone onDrop={this.props.onDrop.bind(this)} accept="image/jpeg, image/png"/>
                <Cropper
                    ref='cropper'
                    src={this.state.image}
                    style={{height: 400, width: 500}}
                    // Cropper.js options
                    aspectRatio={4 / 3}
                    guides={false}
                    preview=".img-preview"
                    autoCropArea={1}
                    crop={this._crop.bind(this)} />
                <View style={styles.previewContainer}>
                <div className="img-preview" style={{ width: 400, height: 300, overflow: "hidden" }} />
                </View>
            </View>
        );
    }


    _crop(){
        // image in dataUrl
        //console.log(this.refs.cropper.getCroppedCanvas().toDataURL());
    }

    _onDrop(files) {
        console.log(files);
        this.setState({image: files[0].preview})
    }
}
```

I think we can close this issue.
