### ISSUE TITLE
Crop SVGs

### ISSUE THREAD

**Issue by adrienharnay** [react-cropper/react-cropper#50]
Hello,

I've been using react-cropper for a while now (awesome by the way), mainly with PNGs, but I was wondering if it were possible to use it with SVGs? Because when I use this.ref.getCroppedCanvas(), I seem to get a PNG.

Thanks in advance!

**Comment by Zephir77167** [comment]
Yes that's one use case I am currently missing, but I'm not aware of the complexity involved
