### ISSUE TITLE
React cropper cannot show the images from firebase with token 

### ISSUE THREAD

**Issue by BPamukcuoglu** [react-cropper/react-cropper#528]
I am using react cropper inside my project. Whenever I try to set src to an image from firebase it doesn't display anything however, when I change the link from any other source like instagram picture it works totally as expected. Also with some other components firebase images work fine. 

https://firebasestorage.googleapis.com/v0/b/zingo-price-labels/o/labels%2Fmigros%2FBG4lzLJskiYkdNwnlM27bKpTqR72_1613393561679.jpg?alt=media&token=f79ec01e-5572-42ea-aabe-7fd402cde153 

You can try this link.

Best,

**Comment by shekhar-shubhendu** [comment]
I checked in a codesandbox and I am getting CORS error in the console. Please check and if that is not the case then please submit a repro codesandbox and I'll try to help.

**Comment by BPamukcuoglu** [comment]
https://codesandbox.io/s/pensive-tdd-0172h
you can check on that. I didn't get any console error. As I mention before image still loads on the browser but not on the cropper.

**Comment by shekhar-shubhendu** [comment]
this is the error that i see when I open this sandbox
![image](https://user-images.githubusercontent.com/9253059/108506833-b9674080-72b9-11eb-8a54-27b1eec676be.png)

**Comment by BPamukcuoglu** [comment]
thanks for your time, you are the best 👍
