### ISSUE TITLE
zoom out in demo not working

### ISSUE THREAD

**Issue by DanielRuf** [react-cropper/react-cropper#551]
**Describe the bug**
On the demo we can not zoom out using two fingers.

**To Reproduce**
1. Go to https://codesandbox.io/s/wonderful-pine-i7fs3
2. zoom image in with two fingers
3. try to zoom out with two fingers

**Expected behavior**
zooming out should work

**Smartphone (please complete the following information):**
 - any smartphone with Chrome on Android

**Comment by DanielRuf** [comment]
I found this, is the demo outdated? Can you update it?

**Comment by shekhar-shubhendu** [comment]
Thanks for bringing this up.
Yeah certainly something seems wrong.
I'll try to fix it when I have some free time at hand. 🙂

**Comment by DanielRuf** [comment]
Forgot to add the relevant link, updated my last comment.
