### ISSUE TITLE
checkCrossOrigin={false} causes: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by developdeez** [react-cropper/react-cropper#552]
I recently tried this component again and notcied that when using any image (Im using the test url)

Im not sure why I keep getting this message. Im attempting to create a window around the cropper so the user can save what they have in frame.

Here's an example: https://codesandbox.io/s/react-cropper-demo-forked-5jehf

I need the flag for my signedURLs (CORs), so removing it isnt an option.

**Comment by developdeez** [comment]
bump

**Comment by MatheusFoganholo** [comment]
Same problem here.

**Comment by shekhar-shubhendu** [comment]
seems like another cropperjs issue
please check there 
https://github.com/fengyuanchen/cropperjs/issues/675

**Comment by developdeez** [comment]
@shekhar-shubhendu it does look related not sure how to solve it in React using their js fix

**Comment by developdeez** [comment]
Are there any good alternatives for react-cropper?
Seems this bug isnt going to be fixed?

**Comment by developdeez** [comment]
Still a bug 
@shekhar-shubhendu , Is this package dead?

**Comment by shekhar-shubhendu** [comment]
https://github.com/fengyuanchen/cropperjs/issues/824
