### ISSUE TITLE
zoomTo={value} option not working

### ISSUE THREAD

**Issue by RFDPrint** [react-cropper/react-cropper#553]
I have tried on several occasions to get the zoomTo={value} option to work.   It worked well in the past, however recently it has stopped working.

**Comment by shekhar-shubhendu** [comment]
unable to repro this.
what value are you passing to to `zoomTo`?
can you please give me a codesandbox that demos the issue

**Comment by RFDPrint** [comment]
Sure, here is an example of the "zoomTo" prop not working as expected. 
https://codesandbox.io/s/react-cropper-with-slider-w7s9i

**Comment by shekhar-shubhendu** [comment]
zoomTo is only applied at initial render i.e. when cropper is initialised.
Try the zoom method on cropper instance if you want to zoom after that.

**Comment by RFDPrint** [comment]
Interesting, I bring this up because the "zoomTo" method was working (even after initialized) on my application for months and then just stopped.  The "zoom" method is expecting a function not a number value, I can dive into it more to make it work but it seems that something broke with "zoomTo" along the way.

**Comment by rizvanua** [comment]
I've found the fix for this issue `  /**
     * do zooming when zoomTo param is changed (passind data to cropperjs)
     */   
 useEffect(() => {
       if(combinedRef.current?.cropper?.canvasData && typeof props?.zoomTo === 'number') {
         const cropper = combinedRef.current.cropper;
         cropper.zoomTo(props.zoomTo);
       }
    },[props.zoomTo]);`

I could create a branch with the fix on the repo but don't have a permission to do this

**Comment by shekhar-shubhendu** [comment]
@rizvanua Thanks.
You can fork and then create a PR from there.

**Comment by shekhar-shubhendu** [comment]
@rizvanua please check the latest beta release and thanks for the PR.

**Comment by HarshalGhadiya** [comment]
const cropperRef = useRef(null);
  const [zoom, setZoom] = useState(1);
  
    // Handle zoom change
  const handleZoomChange = (event) => {
    const newZoom = parseFloat(event.target.value);
    setZoom(newZoom);
    if (typeof cropperRef.current?.cropper !== "undefined") {
      const cropper = cropperRef.current.cropper;
      const currentData = cropper.getData();
      cropper.zoomTo(newZoom);
      const newData = cropper.getData();
      const scaleX = currentData.width / newData.width;
      const scaleY = currentData.height / newData.height;
      const newCanvasData = {
        left: currentData.left / scaleX,
        top: currentData.top / scaleY,
        width: currentData.width / scaleX,
        height: currentData.height / scaleY,
      };
      cropper.setData(newCanvasData);
    }
  };

 <input
          type="range"
          onChange={handleZoomChange}
          min="0.1"
          max="3"
          step="0.1"
          value={zoom}
        />
        
        
   You can Archive this functionality using this logic it works for me.

**Comment by HarshalGhadiya** [comment]
` <input
          type="range"
          onChange={handleZoomChange}
          min="0.1"
          max="3"
          step="0.1"
          value={zoom}
        />`
