### ISSUE TITLE
Is Electron supported?

### ISSUE THREAD

**Issue by sogoogos** [react-cropper/react-cropper#555]
**Describe the bug**
The basic functionality seems not working in Electron. It does not even show the cropping frame. I used the following simple code.

```
import React, { useState } from 'react';
import Cropper from 'react-cropper';
import 'cropperjs/dist/cropper.css';

const ImageCrop = () => {
  const [upImg, setUpImg] = useState();

  const onSelectFile = e => {
    if (e.target.files && e.target.files.length > 0) {
      const reader = new FileReader();
      reader.addEventListener('load', () => setUpImg(reader.result));
      reader.readAsDataURL(e.target.files[0]);
    }
  };

  return (
    <>
      <div>
        <input type="file" accept="image/*" onChange={onSelectFile} />
      </div>
      <Cropper src={upImg} />
    </>
  );
};

export default ImageCrop;

```
**Screenshots**
![Screen Recording 2021-03-20 at 19 26 31 (1)](https://user-images.githubusercontent.com/24484961/111866823-8648c780-89b3-11eb-8646-9be3e3a2b98c.gif)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [elecron]
 - Version [11.0.1]

**Comment by vitorizkiimanda** [comment]
me too~ doesnt work at all in electron based app

**Comment by virinchi-manepalli-trysolvio** [comment]
please open this issue ,I m unable to use cropper in electron.

**Comment by DanGiaime** [comment]
@virinchi-manepalli-trysolvio Try manually importing the css, that fixed it for me.

https://stackoverflow.com/questions/67030246/cropping-js-libraries-do-not-work-in-election/68752693#68752693
