### ISSUE TITLE
aspectRatio not working

### ISSUE THREAD

**Issue by grighth12** [react-cropper/react-cropper#571]
I want to make a crop area ratio that changes with the click of a button. Declared the ratio to state and set it to aspectRatio for the Cropper component.

Like this,
` 
const [ratio, setRatio] = useState(1);
....
<Cropper
         ...
          aspectRatio={ratio}
         ...
                  />
`

However, even if the ratio changes, there is no change in the screen.

I added a button to the demo to set the ratio. but it's not working
Here is codesandbox : https://codesandbox.io/s/react-cropper-ratio-o8p5g?file=/src/Demo.tsx:1319-1900

any solution?

**Comment by shekhar-shubhendu** [comment]
@grighth12 you need to use the cropper instance or ref to change the aspect ratio after initialisation

**Comment by LordTep** [comment]
@shekhar-shubhendu how do I update the aspect ratio after that has been done? Similar to this demo https://fengyuanchen.github.io/cropperjs/ .

In that code .destroy() is called on the instance and then a new one is recreated from image and options.

**Comment by shekhar-shubhendu** [comment]
> @shekhar-shubhendu how do I update the aspect ratio after that has been done? Similar to this demo https://fengyuanchen.github.io/cropperjs/ .
> 
> In that code .destroy() is called on the instance and then a new one is recreated from image and options.
> 

@LordTep Thanks. I will check if this can be also handled. I saw the `setAspectRatio` bit earlier in the cropperjs doc and thought it will do the trick but now I see that it does not work after initialisation.

**Comment by grighth12** [comment]
@LordTep 
I've tried this method, like this,

`{ratio === 1 && <Cropper ... ratio={1} />} {ratip === 4/3 && <Cropper ... ratio ={4/3}`

There was a problem with the screen blinking when the ratio changed.



@shekhar-shubhendu  
As you said, the cropbox element(doucment.querySelector(".cropper-crop-box) could be resized using the cropper's ref. However, when clicking, moving, zooming in, or shrinking the cropBox, there was a problem that the cropBox size returned to its original size.

It's not a completely accurate code, but I did it like this.

![image](https://user-images.githubusercontent.com/68159627/116508302-ff650400-a8fb-11eb-8207-a4a7ee0eb069.png)

simple codesandbox: https://codesandbox.io/s/react-cropper-ratio-o8p5g?file=/src/Demo.tsx
Clicking the button changes the size of the cropBox(120px * 120px), but when you click the cropBox returns to its original size.

**Comment by LordTep** [comment]
@shekhar-shubhendu cool thanks,
@grighth12 I actually right now just thought of that. Destroying the whole react component and recreating with a new aspect ratio. Because I have the same problem with the preview window, it does not seem to update it's position on aspect change... Nice one! A flicker could be hidden behind some loading overlay I guess.

**Comment by shekhar-shubhendu** [comment]
is this something that you want?
https://codesandbox.io/s/react-cropper-ratio-forked-tn18k?file=/src/Demo.tsx

**Comment by LordTep** [comment]
@shekhar-shubhendu that's perfect! Thanks

**Comment by grighth12** [comment]
@shekhar-shubhendu Thank you!!!!!!!!!!! <3<3 That's exactly what I wanted!!!
