### ISSUE TITLE
Rotation bug

### ISSUE THREAD

**Issue by amitava82** [react-cropper/react-cropper#578]
react-cropper is applying default rotation 0 even if no rotation value is provided. This brakes when image has exif rotation. Rotation should not be applied unless provided. I'll create a PR.

https://github.com/react-cropper/react-cropper/blob/d5f5a36d7adc9fac6ba6bbc3cd5b96deb737117a/src/react-cropper.tsx#L35

**Comment by KuschL** [comment]
push! 👍

**Comment by amitava82** [comment]
Updated

**Comment by shekhar-shubhendu** [comment]
the new beta release has this fix.
Please check.
