### ISSUE TITLE
cropBoxData issue

### ISSUE THREAD

**Issue by maxim-kolesnikov** [react-cropper/react-cropper#59]
Hi, I am experiencing a problem with `cropBoxData`.

`
          <ReactCropper
            cropBoxData={cropData}
            src={backgroundImage}
            style={styles.cropping}
            guides={false}
            ref={(c) => {
              this.cropper = c;
            }}
          />
`

In my code `cropData` is object example `{left: 72, top: 88, width: 576, height: 324}`

No warnings or errors, just doesn't work.

**Comment by roadmanfong** [comment]
HI,
It seems `cropBoxData` can't be set when start.
Could you try to set it like

```js
componentDidMount() {
  setTimeout(()=>{
    const cropBoxData = { left: 72, top: 88, width: 576, height: 324 };
    this.setState({ cropBoxData });
  }, 0)
}
```

**Comment by mxklsn** [comment]
Yes, it was helpful! 
Do you plan to fix this problem in future?

**Comment by orloffv** [comment]
@roadmanfong up

**Comment by jbalboni** [comment]
We were able to avoid this by setting the crop box data inside a `ready` event callback. It seems like you need to wait for the image to load to set that.

The 0s timeout workaround will fail if you pass a data url to `src` that the browser hasn't loaded or read yet.
