### ISSUE TITLE
Change `Image Cropper` link in README to cropperjs (not cropper)

### ISSUE THREAD

**Issue by dora1998** [react-cropper/react-cropper#599]
`Image Cropper` link in README leads to [fengyuanchen/cropper](https://github.com/fengyuanchen/cropper).
However, the repository is deprecated, and also react-cropper uses [fengyuanchen/cropperjs](https://github.com/fengyuanchen/cropperjs).

This may be confusing for library beginners, so why don't we change this link to cropperjs?

**Comment by shekhar-shubhendu** [comment]
thanks.
Added the correct url.
