### ISSUE TITLE
disable property doesn't work

### ISSUE THREAD

**Issue by mysuf** [react-cropper/react-cropper#612]
react-cropper docs Options include `disable` property (while js library has only method). I tried both `disable={true} `and `onInitialized={(instance) => {  intance.disable() }}`, but without any effect. I can drag/resize/zoom. I want to use it only as a preview link to fully working Cropper in modal dialog. Thanks

**Comment by mysuf** [comment]
Also `data `property is omitted even when `autoCrop={true}`.

console.log of props passed to new Cropper inside react-cropper.umd.js:
```
aspectRatio: 0.5625
autoCrop: true
background: false
checkOrientation: false
data: {x: 0, y: 0, width: 596.8124999999999, height: 1061, rotate: 0, …}
dragMode: "crop"
guides: true
minCropBoxHeight: 432
minCropBoxWidth: 432
ready: ƒ (e)
responsive: true
viewMode: 1
```

So it looks more like cropperjs issue.

I checked also cropper.destroy() of cleanup function in useEffect and it isn't called at all

**Comment by khanhhaquang** [comment]
Having the same issue, hope there will be a new update for the `disable` props

**Comment by shekhar-shubhendu** [comment]
@mysuf @khanhhaquang for disabling have you tried setting `enable={false}` ?
@mysuf I'll look into the data issue.

**Comment by khanhhaquang** [comment]
> @mysuf @khanhhaquang for disabling have you tried setting `enable={false}` ?
> @mysuf I'll look into the data issue.

`enable` prop works for me
