### ISSUE TITLE
Trying to restore previous crop data

### ISSUE THREAD

**Issue by orderwerks** [react-cropper/react-cropper#624]
I'm using v2.1.7 and when I pull the crop data using cropperRef.getData() and then pass this to the component property `data`, the previous crop data doesn't restore on the image:

```
<Cropper
    data={previousCropData}
    />
```

I've also tried setting this using the onInitialized callback, but same issue:

```
<Cropper
    onInitialized={(instance) => {
        instance.setData(previousCropData);
    }}
/>
```

I've also tried passing in `getCropBoxData()` object as well to the same effect. Am I doing this correctly? or is this broken?

Thanks.

**Comment by shekhar-shubhendu** [comment]
@orderwerks Thanks for reporting this. If you can make me a codesandbox with the issue, I can look into it and check what is the issue.

**Comment by SpencerRohan** [comment]
If you utilize the demo and add `data={{
            height: 140,
            rotate: 45,
            scaleX: 1,
            scaleY: 1,
            width: 140,
            x: 21,
            y: 56
          }}` it appears not to do anything.

**Comment by srohan-nerdery** [comment]
This seems resolved now on v2.1.8

**Comment by SpencerRohan** [comment]
This now seems resolved with v2.1.8

**Comment by orderwerks** [comment]
There still is a bug with it...

set the package.json in the demo to 2.1.8,

and set the data to:

```
data={{
  height: 400,
  rotate: 0,
  scaleX: 1,
  scaleY: 1,
  width: 400,
  x: 100,
  y: 0
}}
```
The crop box won't restore to y = 0. It respects x = 0, but for some reason won't allow y = 0.

**Comment by SpencerRohan** [comment]
![Screen Shot 2021-06-30 at 12 48 57 PM](https://user-images.githubusercontent.com/10297991/124008033-994f3880-d9a1-11eb-9e41-bd588c89bce7.png)

@orderwerks  I am getting it to work with the data provided above. Did you try and hit the refresh button inside the preview window(dumb question)?  2.1.7 definitely didn't work.

**Comment by orderwerks** [comment]
Definitely hit refresh, multiple times:

![image](https://user-images.githubusercontent.com/70450338/124053014-4b9ff380-d9d4-11eb-8da1-83dbf54c686d.png)

**Comment by shekhar-shubhendu** [comment]
Please check this: https://codesandbox.io/s/exciting-pond-mncz0?file=/src/Demo.tsx

**Comment by SpencerRohan** [comment]
I was able to reproduce what @orderwerks is getting on 2.1.8, it appears the positioning changes between screen widths. 

To Reproduce:
1. Set data property to above.
2. Refresh preview
3. Make browser window smaller
4. Refresh preview

 It most certainly doesn't look like the set data button in @shekhar-shubhendu link, but the set data workaround does work for me.
