### ISSUE TITLE
Problem with initial cropper width calculation when display: none applied

### ISSUE THREAD

**Issue by pospieszynski** [react-cropper/react-cropper#63]
I try to implement simple cropper slider. In my app I can upload some image files and these are mapped into cropper components. Only one component is displayed at a time, I can use arrows to display next one etc.

All of the components are present in the DOM, I just hide components with display: none property.
On the bottom, preview images are displayed.

the render function looks like this: 

```  
_renderCroppers () {
    return this.state.files.map( (file, index) => {
      return (
        <Cropper ref={this._bindRef}
                 key={`cropper-${index}`}
                 className={cn({'hide' : this.state.currentCropper !== index})}
                 preview={`.grid-item-${index}`}
                 responsive={true}
                 src={file.preview}
                 viewMode={3}
                 aspectRatio={16/9}
        />
        );
    });
  }
```

Now, the problem is that when the Cropper component is initialized with display: none and then i get rid of this property(i.e by clicking next arrow) its size is different(width: 200px) from component that was initialized without display: none applied on it(has width 100%).

**1. After uploading 2 images - first cropper is displayed correctly.**
![screenshot from 2017-03-21 01-34-54](https://cloud.githubusercontent.com/assets/15077823/24126457/c08d100c-0dd6-11e7-898e-da891d1d899e.png)

**2. After pressing next arrow (changing currentCropper state) the size is different:** 
![screenshot from 2017-03-21 01-35-18](https://cloud.githubusercontent.com/assets/15077823/24126458/c08e4c10-0dd6-11e7-9d0d-2b243f56b298.png)

When there is no display none applied, all of the croppers are rendered with proper width (100%), so how does cropper calculate its width initially?

Does anyone has a clue why it behaves like this?

**Comment by dhirendrarathod2000** [comment]
@pospieszynski not an elegant solution but you can manually try to trigger window.resize
this is just a wrapper for https://github.com/fengyuanchen/cropperjs
look at the responsive property of that
https://github.com/fengyuanchen/cropperjs#responsive
