### ISSUE TITLE
Right Types For Refs

### ISSUE THREAD

**Issue by EduardoAraujoB** [react-cropper/react-cropper#642]
# Problem
Currently the documentation recommends to set the cropper ref types as `HTMLImageElement`, then the user try to use the `getCroppedCanvas` function from the ref and got a type error saying that `HTMLImageElement` doesn't have the `getCroppedCanvas` function (and it doesn't), so the types are wrong and it's forcing the users to type their constants as any which is bad

# Solution
so if the types of the reference is  a modified version of the `HTMLImageElement`, then the solution is simple, extend that type and then add the definitions and overrides that the cropper is doing over it (which is what I'm doing locally in my project to fix it)

**Comment by shekhar-shubhendu** [comment]
@EduardoAraujoB Thanks for bringing this up. Currently, I have made ReactCropperElement extending HTMLImageElement but I think I did not expose the correct types for it. I will check and make a small release.

**Comment by EduardoAraujoB** [comment]
@shekhar-shubhendu thanks, I will be waiting the release to replace the local types that I made as a workaround for this problem

**Comment by shekhar-shubhendu** [comment]
okay. so it works in the current version too. just import `ReactCropperElement` and use that instead of `HTMLImageElement`

**Comment by EduardoAraujoB** [comment]
worked, thanks a lot
