### ISSUE TITLE
Breaks on Safari 

### ISSUE THREAD

**Issue by firaskrichi** [react-cropper/react-cropper#65]
Hi, I'm getting an error when trying to crop on Safari : 

TypeError: this.refs.debAddBillCropper.getCroppedCanvas({fillColor:"#FFFFFF"}).toBlob is not a function. (In 'this.refs.debAddBillCropper.getCroppedCanvas({fillColor:"#FFFFFF"}).toBlob(function(t){var n=new FormData;n.append("bill",t),(0,c.addBill)(n,e)})', 'this.refs.debAddBillCropper.getCroppedCanvas({fillColor:"#FFFFFF"}).toBlob' is undefined)

It works totally fine on Chrome & Firefox, but breaks on Safari. 

Any ideas why?

**Comment by dougshamoo** [comment]
@firaskrichi `toBlob` requires a polyfill on safari it seems. I chose to use this one: https://github.com/blueimp/JavaScript-Canvas-to-Blob.
