### ISSUE TITLE
Cannot get image data

### ISSUE THREAD

**Issue by djfdev** [react-cropper/react-cropper#67]
I have a cropper component inside of a fixed-width div. I'd like to make sure that the height of the cropper container matches the height of the image.

I thought I could do this by grabbing the image data after the component mounts, calculating the aspect ratio from the natural dimensions, and then calculating the appropriate height to match the actual width of the image.

```js
class Cropper extends Component {
  constructor (props) {
    super(props)
    this.state = {}
  }

  componentDidMount () {
    const imageData = this.refs.cropper.getImageData()

    const aspectRatio = imageData.naturalWidth / imageData.naturalHeight
    const containerHeight = imageData.width / aspectRatio

    this.setState({ containerHeight })
  }

  getCropperStyles () {
    const styles = { width: '100%' }

    if (this.state.containerHeight) {
      styles.height = this.state.containerHeight
    }

    return styles
  }

  render () {
    return <ReactCropper ref='cropper' src={this.props.src} styles={this.getCropperStyles()} />
  }
}
```

But when I do this, `this.refs.cropper.getImageData()` doesn't seem to return what I'm expecting. I think this has to do with the fact that the image has not actually loaded even when `componentDidMount` is called. Is there a callback I can pass in as a prop to update my component's state when the image loads?

**Comment by ambroseya** [comment]
Did you get a solution for this? I'm looking for this same thing.
