### ISSUE TITLE
Image re-initialize set incorrect width and height when I implement it with antd modal 

### ISSUE THREAD

**Issue by jemink** [react-cropper/react-cropper#674]
I used the `react-cropper` `v2.1.7`. In that I added one cropper component and three preview div to display to preview and on the create button I am going to upload the crop image on my cdn server and close the modal and when I reopen the modal with uploaded crop image then It will set incorrect width and height on image also preview is disable (Because it will set image width as 0). I used this on antd modal component. But when I refresh the page and reopen the modal then it will set correctly. But I want to set correctly without refreshing

Video url:- https://www.awesomescreenshot.com/video/4710256?key=da84c1d0734c2c40d980fae8dfead64b

**Comment by jemink** [comment]
Issue resolved.

**Comment by blackcat1323** [comment]
@jemink I also got the same error, how did you solve it? thanks in advance
