### ISSUE TITLE
Large images on Android: slow performance

### ISSUE THREAD

**Issue by dotfury** [react-cropper/react-cropper#70]
Is there a work flow to get this to work with larger images(~12MB)? For instance if the user takes a picture on an Android device, the image may be really large, and if they chose it to crop it can be less than optimal. Are there any settings for things like this? I didn't see/notice anything that could be related to this in the docs. Just wanted to double check. Thanks

**Comment by sethkrasnianski** [comment]
I'm also running into this issue with iOS. The generated data URI is massive.

**Comment by herechc** [comment]
me too, do you resolve?

**Comment by dotfury** [comment]
No, didn't resolve. I think we made the account sign-up flow desktop only in the end. The mobile experience was just that slow for cropping.
