### ISSUE TITLE
max cropBox width and height

### ISSUE THREAD

**Issue by philmetzger** [react-cropper/react-cropper#701]
How come there is no maxCropBoxWidth or maxCropBoxHeight?

As a user I would like to set the max width and height of the image to be cropped. For example the image cropped should be max 200px wide.

**Comment by shekhar-shubhendu** [comment]
@philmetzger It is not there since cropperjs doesn't provide it. Here is the reason and a solution https://github.com/fengyuanchen/cropperjs/issues/831
