### ISSUE TITLE
crop the image in circle shape

### ISSUE THREAD

**Issue by sudarshan55** [react-cropper/react-cropper#707]
For cropping image in circle I have reffered this 

https://github.com/fengyuanchen/cropper/issues/545

It does seems to work in most of the cases. But, when I used mutliple instances 
of image-cropper in the single page then it doesn't seems to work.  

Although, I tried keeping both the instances isolated by using two separate components, but the CSS affects both the instances which are mounted currently.

So, is there any robust solution for this problem?

**Comment by shekhar-shubhendu** [comment]
AFAIK, this is not exactly possible but it would be a good idea to check/ask [here](https://github.com/fengyuanchen/cropperjs/issues) instead

**Comment by dyyd** [comment]
Would love to see this be a thing.  Have seen similar option on other cropping libraries.
Seeing as it is doable with CSS change it would be nice if this library provided the convenience method for it.
