### ISSUE TITLE
How do I change the size of the cropper UI?

### ISSUE THREAD

**Issue by wilsonrocks** [react-cropper/react-cropper#730]
Sorry about raising an issue for this - I wasn't sure how else to ask.

I'm using react-cropper on a generator for game pieces - works great, except how do I change the size of the cropper UI. E.g. I'd like to reserve say 400px by 400px for the cropper, both before the user has loaded an image and if they change the image.

No matter what I do with CSS or options from the docs, the UI seems to resize itself according to the image. Apologies if I've missed something really obvious!

James

**Comment by shekhar-shubhendu** [comment]
not sure but is this what you want https://github.com/fengyuanchen/cropperjs/issues/873
