### ISSUE TITLE
Add an onLoad event to know when the image is ready

### ISSUE THREAD

**Issue by BerenLuth** [react-cropper/react-cropper#735]
**Problem:**
When i try to work on a heavy picture (or any picture with slow connection) the cropper stays completely white until the image is fully loaded, and for the user this seems like nothing is happening and the website is stuck.

**Solution:**
An event that gets triggered when the picture is loaded, so it would be possible to handle the UI accordingly.

**Possible alternative:**
If exposing a callback is not possible or doesn't fit the roadmap for this library, an internal loading would be ok as well, but it wouldn't be so flexible in terms of creating a coherent UI.

**Additional context:**
The img tag already offers an event trigger called "onload" to understand when the image is ready, but I didn't manage to make it work in react since i had to go through the cropper reference to get to the internal img, and i couldn't set the event properly, maybe it was my fault, but in general I think that if there was an event available in the Cropper object, then it would keep the code much cleaner.

**Comment by BerenLuth** [comment]
@shekhar-shubhendu thank you so much for the attention.

In my case I'm trying to access pictures from an aws s3 bucket, It happens with every image if it's big enough (in terms of bytes) and/or the connection is slow (on firefox I use the Responsive design mode, that allows me to simulate a slower connection).

**Comment by shekhar-shubhendu** [comment]
Now, I'm applying all the image props to the img tag.
I'll create a preview release for now with this change and you can try and give me feedback if everything works as expected. 🙏🏾 

sandbox example: https://codesandbox.io/s/react-cropper-demo-forked-nsidd
