### ISSUE TITLE
rotateTo prop don't work

### ISSUE THREAD

**Issue by alexander-gvozd** [react-cropper/react-cropper#762]
I have input range that must change image rotation. If i set initial rotation for example 90deg then image will rotated. But if I am using my range bar, image will not be rotated. I expect what i will can to change it using range.

Some fragments from my code
```

const [rotate, setRotate] = React.useState(90);

<Cropper
  src={imageRaw}
  style={{ height: 400, width: "100%" }}
  // Cropper.js options
  initialAspectRatio={aspectRation}
  guides={false}
  crop={onCrop}
  ref={cropperRef}
  aspectRatio={aspectRation}
  viewMode={3}
  zoomTo={zoom}
  zoomOnWheel={false}
  toggleDragModeOnDblclick={false}
  dragMode={"move"}

  rotatable={true}
  rotateTo={rotate}
/>

<Form.Group>
  <Form.Label>Rotate</Form.Label>

  <Form.Range
    value={rotate}
    min={0}
    max={360}
    step={1}
    onChange={(e) => {
      setRotate(parseFloat(e.currentTarget.value));
    }}
  />
</Form.Group>
```

**Comment by shekhar-shubhendu** [comment]
Best would be to use the `rotate` or `rotateTo` methods directly from the `cropperRef` that you have declared.
- `cropperRef.current.rotate(input)`
- `cropperRef.current.rotateTo(input)`

Ref: https://github.com/fengyuanchen/cropperjs/#rotatedegree
