### ISSUE TITLE
A way to enforce 16x9 aspect ratio

### ISSUE THREAD

**Issue by kodeschooler** [react-cropper/react-cropper#767]
I would simply like to know if there's a way using this library to enforce a 16x9 aspect ratio?. Where someone can upload any image and crop it but it needs to be uploaded as 16x9. I notice there is an initialAspectRatio prop as an initial ratio. But can you make sure it stays that aspect ratio? We can't have any images that are not in that ratio.  

Thank you very much!

**Comment by shekhar-shubhendu** [comment]
Have you tried this https://github.com/fengyuanchen/cropperjs#aspectratio
