### ISSUE TITLE
Need circular cropping functionality

### ISSUE THREAD

**Issue by virat07** [react-cropper/react-cropper#807]
As I'm trying to use this component as a profile upload I was looking for something like a circular resize/crop but right now it doesn't support that feature. Also when I resize it, it gets not resize as a circle radius but according to width and height (added an image below). An example is added below for a reference of the required feature. 
https://fengyuanchen.github.io/cropperjs/examples/crop-a-round-image.html
![image](https://user-images.githubusercontent.com/36244814/148025157-276a3af7-5dc5-43e1-883e-464ff0001871.png)

**Comment by virat07** [comment]
@shekhar-shubhendu  can you please help ?

**Comment by junzero741** [comment]
any update?
