### ISSUE TITLE
Preview Identical for Any Image

### ISSUE THREAD

**Issue by LoganArnett** [react-cropper/react-cropper#91]
Trying to get the preview displayed in the cropper to always fit within a 400x400 box, regardless of the resolution of the file I need the preview to be a square and the preview to not be skewed. Is there simple way to accomplish this? Or is this a question for the `Cropperjs` repo?

**Comment by ambroseya** [comment]
You should be able to apply your size requirements to the wrapping div that is around the react-cropper component -- at least that's how I have used it successfully. I have applied max-width and max-height to the bounding div. Keeping the preview from skewing is a matter of your component settings, and a separate issue.
