### ISSUE TITLE
Is This Package Still Maintained ?

### ISSUE THREAD

**Issue by Aetherall** [react-cropper/react-cropper#95]
It's been months since the last commit, Is it still safe to use ?
Will cropperjs updates be applied to react-cropper ?
Should we use another package ?

Thanks !

**Comment by ipiz** [comment]
It is still using "cropperjs": "v1.0.0-rc.3"
We need to update to latest cropperjs

**Comment by hanzichi** [comment]
seems not maintained, what's your chioce @Aetherall

**Comment by Aetherall** [comment]
@hanzichi I think i did used directly cropperjs through a react component, but there might be another alternative by now i suppose

**Comment by roelbarreto** [comment]
I Did use cropperjs directly too and create my own component to wrap it, added only features I needed.

https://gist.github.com/roelbarreto/752c3152dd0a6bda61e849ca48d6dff5

**Comment by hanzichi** [comment]
@Aetherall @roelbarreto  I need to use the `maxWidth` option of `getCroppedCanvas`, but react-cropper does not support, so I made another wrapper too, but I find another issue while using [cropperjs](https://github.com/fengyuanchen/cropperjs), have you ever met it?  The issue is <https://github.com/fengyuanchen/cropperjs/issues/507>

**Comment by roelbarreto** [comment]
@hanzichi its fine in chrome, it has bug on firefox. Your issue on https://github.com/fengyuanchen/cropperjs/issues/507 is isolated to firefox

**Comment by hanzichi** [comment]
@roelbarreto  not really, my screenshot is on my chrome

**Comment by roelbarreto** [comment]
if you set checkorieintation to false, it work fine.

`checkOrientation: false`

https://jsfiddle.net/v6Lgdkaw/

I think there is bug there that if the image has orientation auto rotate property, the library don't detect or has bug on it.

**Comment by hanzichi** [comment]
@roelbarreto after setting `checkOrientation: false`, it changes my original dirction of my picture, that's not what I want

**Comment by frisi** [comment]
@roadmanfong - you created a new release in sept. 2019 (https://github.com/roadmanfong/react-cropper/commit/1a64b3264f995cf5ebb0ae199ab74537f7f20952) after this ticket has been opened. 

as you own this repository could you please answer the following question:

do you still (plan to) maintain this package (= answer issues, review+merge pull requests)?
