### ISSUE TITLE
Cropper Adjustment Happening Very Slowly

### ISSUE THREAD

**Issue by sutriptaroy** [react-cropper/react-cropper#98]
i'm using react-cropper package. all are working fine. but when selecting the crop area, the transition of the area boundary or changing the crop area or selecting the desired crop area happening very very slowly. thus selection of the correct portion of the image is taking lots of time.

**Comment by shacco** [comment]
Hi!
Im using react-cropper as well. I a shame you guys does not take this seriously.

@sutriptaroy . I think you need to set up debounce on crop event. See the thing when you do this
 <Cropper
                                ref='cropper'
                                crop={this._crop}/>

  this._crop=debounce(this._crop.bind(this),250);

The crop happens to many times. I did it, and everything went better. But, it is o enough. The crops are still to fast when you scroll the image. So im welcome to any suggestion. 


thanks

**Comment by shacco** [comment]
Another way is to use cropend event instead. But the effect will not be real time

**Comment by limistah** [comment]
> Another way is to use cropend event instead. But the effect will not be real time

I owe you a bottle of bear for this.

**Comment by shacco** [comment]
jaja wich country are you from? I may be take that offer some day.
