### ISSUE TITLE
Image Size increasing while cropping the whole image

### ISSUE THREAD

**Issue by botxboom** [react-cropper/react-cropper#985]
Before creating a bug/issue here please check that it is not part of cropperjs and does not exist [in the cropperjs repo](https://github.com/fengyuanchen/cropperjs/issues).

**Describe the bug**

**To Reproduce**
1. Go to 'react-cropper demo page'
2. Click on 'upload a picture'
3. select whole image by dragging the cropping area
4. Hit Crop Button
5. Save cropped image and check the size

**Expected behavior**
It's size should have remained same or lower than the orizinal file size.

**Current behaviour**
It's size increasing by multiple times.

**Comment by bz0wski** [comment]
I facing the same issue, I upload a file with size 700KB and when I crop just the head, the cropped image comes out at 5MB. I am storing these images on a cloud service and so would as much as possible like for the cropped image to have a small size. Also my target market is in Africa where internet speeds are quite slow so this will negatively impact UX. Can you please indicate what can be done to reduce the image size ? 

PS: you made a really awesome tool, thanks.

**Comment by bz0wski** [comment]
> I facing the same issue, I upload a file with size 700KB and when I crop just the head, the cropped image comes out at 5MB. I am storing these images on a cloud service and so would as much as possible like for the cropped image to have a small size. Also my target market is in Africa where internet speeds are quite slow so this will negatively impact UX. Can you please indicate what can be done to reduce the image size ?
> 
> PS: you made a really awesome tool, thanks.

For anyone who comes across this and has the same question, I used the code here: https://github.com/fengyuanchen/cropperjs/blob/main/docs/examples/crop-a-round-image.html that generates a rounded image to generate a smaller image by manually setting the 
```
canvas.width
canvas.height
```
This way I end up with much smaller file sizes of the generated images.
